#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : perl-XML-Parser
Version  : 2.46
Release  : 49
URL      : https://cpan.metacpan.org/authors/id/T/TO/TODDR/XML-Parser-2.46.tar.gz
Source0  : https://cpan.metacpan.org/authors/id/T/TO/TODDR/XML-Parser-2.46.tar.gz
Summary  : 'A perl module for parsing XML documents'
Group    : Development/Tools
License  : Artistic-1.0-Perl
Requires: perl-XML-Parser-perl = %{version}-%{release}
BuildRequires : buildreq-cpan
BuildRequires : expat-dev
BuildRequires : perl(Encode::Locale)
BuildRequires : perl(LWP)
BuildRequires : perl(LWP::UserAgent)
BuildRequires : perl-LWP-MediaTypes

%description
NAME
XML::Parser - A perl module for parsing XML documents
SYNOPSIS
use XML::Parser;

%package dev
Summary: dev components for the perl-XML-Parser package.
Group: Development
Provides: perl-XML-Parser-devel = %{version}-%{release}
Requires: perl-XML-Parser = %{version}-%{release}

%description dev
dev components for the perl-XML-Parser package.


%package perl
Summary: perl components for the perl-XML-Parser package.
Group: Default
Requires: perl-XML-Parser = %{version}-%{release}

%description perl
perl components for the perl-XML-Parser package.


%prep
%setup -q -n XML-Parser-2.46
cd %{_builddir}/XML-Parser-2.46

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
if test -f Makefile.PL; then
%{__perl} Makefile.PL
make  %{?_smp_mflags}
else
%{__perl} Build.PL
./Build
fi

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make TEST_VERBOSE=1 test

%install
rm -rf %{buildroot}
if test -f Makefile.PL; then
make pure_install PERL_INSTALL_ROOT=%{buildroot} INSTALLDIRS=vendor
else
./Build install --installdirs=vendor --destdir=%{buildroot}
fi
find %{buildroot} -type f -name .packlist -exec rm -f {} ';'
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null ';'
find %{buildroot} -type f -name '*.bs' -empty -exec rm -f {} ';'
%{_fixperms} %{buildroot}/*

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/share/man/man3/XML::Parser.3
/usr/share/man/man3/XML::Parser::Expat.3
/usr/share/man/man3/XML::Parser::Style::Debug.3
/usr/share/man/man3/XML::Parser::Style::Objects.3
/usr/share/man/man3/XML::Parser::Style::Stream.3
/usr/share/man/man3/XML::Parser::Style::Subs.3
/usr/share/man/man3/XML::Parser::Style::Tree.3

%files perl
%defattr(-,root,root,-)
/usr/lib/perl5/*
